backend/crm/urls.py
from django.urls import path

urlpatterns = [
]

backend/erp/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt import views as jwt_views   

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/token', jwt_views.TokenObtainPairView.as_view()),
    path('', include('core.urls')),
    path('crm/', include('crm.urls')),
    path('accounting/', include('accounting.urls')),
    path('employee/', include('employee.urls')),
    path('sales/', include('sales.urls')),
    path('mfr/', include('manufacturing.urls')),
    path('purchase/', include('purchase.urls')),
    path('stock/', include('stock.urls')),
]

backend/purchase/urls.py
from django.urls import path, include

from .views import *

urlpatterns = [
    path('search-product', ProductAsyncSearchView.as_view()),
    path('search-stock-location', StockLocationAsyncSearchView.as_view()),
    path('search-expense-type', ExpenseTypeAsyncSearchView.as_view()),
    path('search-supplier', SuppilerAsyncSearchView.as_view()),
    path('search-employee', EmployeeAsyncSearchView.as_view()),
    path('search-bank-account', BankAccountAsyncSearchView.as_view()),
    path('order/', include('purchase.components.order.urls')),
]

backend/sales/components/order/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter

from .views import *

urlpatterns = [
    path('search', OrderTableView.as_view()),
]

router = DefaultRouter()
router.register('crud', OrderViewSet)
urlpatterns += router.urls

backend/purchase/models.py
from django.db import models
from django.utils.translation import gettext as _
from accounting.models import Invoice, Ledger, LedgerItem, ExpenseType
from core.models import Company, Partner, User
from stock.models import Import, Export, Product, ProductMove
from .constants import OrderStatus, OrderType

class Order(models.Model):
    company = models.ForeignKey(Company, 
        on_delete=models.PROTECT, 
        related_name='company_pu_orders'
    )

    order_number = models.CharField(max_length=100)

    type = models.CharField(choices=OrderType.choices(), max_length=50)

    ref_order = models.ForeignKey('Order', 
        blank=True, null=True, 
        on_delete=models.PROTECT
    )

    supplier = models.ForeignKey(Partner, 
        on_delete=models.PROTECT, 
        related_name='supplier_pu_orders'
    )

    ledger = models.OneToOneField(Ledger, 
        related_name='ledger_pu_order',
        on_delete=models.CASCADE
    )

    expense = models.IntegerField()
    amount_untaxed = models.IntegerField()
    amount_tax = models.IntegerField()
    amount = models.IntegerField()
    
    invoice = models.OneToOneField(Invoice,
        related_name='invoice_pu_order',
        blank=True, null=True,
        on_delete=models.CASCADE
    )

    _import = models.OneToOneField(Import,
        related_name='import_pu_order',
        blank=True, null=True,
        on_delete=models.CASCADE
    )

    _export = models.OneToOneField(Export,
        related_name='export_pu_order',
        blank=True, null=True,
        on_delete=models.CASCADE
    )

    note = models.CharField(max_length=500, blank=True)

    request_person = models.ForeignKey(User, related_name='request_pu_orders', 
            blank=True, null=True,
            on_delete=models.PROTECT)

    approve_person = models.ForeignKey(User, related_name='approve_pu_orders', 
            blank=True, null=True,
            on_delete=models.PROTECT)

    request_date = models.DateTimeField(blank=True, null=True)
    approve_date = models.DateTimeField(blank=True, null=True)
    order_date = models.DateTimeField(blank=True, null=True)
    receive_date = models.DateTimeField(blank=True, null=True)
    
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    status = models.CharField(choices=OrderStatus.choices(), 
        default=OrderStatus.DRAFT.name,
        max_length=50
    )

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    
    product = models.ForeignKey(Product, 
        related_name='product_pu_order_items',
        on_delete=models.PROTECT
    )

    qty = models.IntegerField()
    price_unit = models.IntegerField()
    discount = models.IntegerField()
    amount_tax = models.IntegerField()
            
    ledger_item = models.OneToOneField(LedgerItem,
        related_name='ledger_pu_order_item',
        on_delete=models.PROTECT
    )

    product_move = models.OneToOneField(ProductMove,
        blank=True, null=True,
        related_name='product_move_pu_order_item',
        on_delete=models.PROTECT
    )

    @property
    def amount_untaxed(self):
        return self.qty * self.price_unit - self.discount

class OrderItemTax(models.Model):
    order_item = models.ForeignKey(OrderItem, on_delete=models.CASCADE)
        
    ledger_item = models.OneToOneField(LedgerItem,
        related_name='ledger_pu_order_item_tax',
        on_delete=models.PROTECT
    )

class OrderExpense(models.Model):
    order = models.ForeignKey(Order, related_name='expenses', on_delete=models.CASCADE)
    
    type = models.ForeignKey(ExpenseType, 
        related_name='expense_type_pu_order_expenses',
        on_delete=models.PROTECT
    )

    note = models.CharField(max_length=500, blank=True)

    ledger_item = models.OneToOneField(LedgerItem,
        related_name='ledger_pu_order_expense',
        on_delete=models.PROTECT
    )

backend/purchase/components/order/views.py
from core.utils.viewsets import ModelViewSet
from core.views_api import DataTableView
from purchase.models import Order

from purchase.constants import OrderStatus
from .serializers import *

class OrderViewSet(ModelViewSet):
    serializer_class = OrderSerializer
    queryset = Order.objects.all()

class OrderTableView(DataTableView):
    model = Order
    order_by = '-update_date'
    columns_def = [
        {
            'name': 'order_number',
            'title': 'Số đơn hàng',
            'width': '24%',
        },
        {
            'name': 'supplier',
            'display_field': 'name',
            'title': 'Nhà cung cấp',
            'width': '24%'
        },
        {
            'name': 'note',
            'title': 'Ghi chú',
            'orderable': False,
            'width': '24%'
        },
        {
            'name': 'status',
            'display_list': OrderStatus.choices(),
            'title': 'Trạng thái',
            'orderable': False,
            'width': '24%'
        },
        {
            'title': 'Thao tác',
            'orderable': False,
            'search': False,
            'css_class': 'text-center',
            'width': '4%'
        },
    ]

    def get_queryset(self, user, params):
        type_ = params.get('type', '')
        return Order.objects.filter(company=user.employee.company, type=type_.upper())

backend/purchase/components/return/views.py
from core.views_api import DataTableView
from purchase.models import Order
from core.constants import BaseStatus

class ReturnTableView(DataTableView):
    model = Order
    order_by = '-update_date'
    columns_def = [
        {
            'name': 'order_number',
            'title': 'Số đơn hàng',
            'width': '24%',
        },
        {
            'name': 'supplier',
            'display_field': 'name',
            'title': 'Nhà cung cấp',
            'width': '24%'
        },
        {
            'name': 'note',
            'title': 'Ghi chú',
            'orderable': False,
            'width': '24%'
        },
        {
            'name': 'status',
            'display_list': BaseStatus.choices(),
            'title': 'Trạng thái',
            'orderable': False,
            'width': '24%'
        },
        {
            'title': 'Thao tác',
            'orderable': False,
            'search': False,
            'css_class': 'text-center',
            'width': '4%'
        },
    ]

    def get_queryset(self, user):
        return Order.objects.none()

backend/purchase/views.py
from django.db.models import Q

from core.models import Partner
from employee.models import Employee
from accounting.models import ExpenseType, BankAccount
from stock.models import Product, Location as StockLocation
from core.views_api import AsyncSearchView, DataAsyncSearchView
from core.constants import BaseStatus
from accounting.constants import BankAccountType

class ProductAsyncSearchView(DataAsyncSearchView):
    model = Product
    fields = ['name', 'price_unit']

    def get_price_unit(self, item, context):
        return item.list_price

class StockLocationAsyncSearchView(DataAsyncSearchView):
    model = StockLocation
    fields = ['name']

class SuppilerAsyncSearchView(AsyncSearchView):
    fields = ['name']

    def get_queryset(self, term, request):
        company = request.user.employee.company
        return Partner.objects.filter(
            company=company,
            is_supplier=True,
            name__icontains=term,
            status=BaseStatus.ACTIVE.name
        )

class EmployeeAsyncSearchView(AsyncSearchView):
    fields = ['name']

    def get_name(self, item, context):
        return item.user.display

    def get_queryset(self, term, request):
        company = request.user.employee.company
        return Employee.objects.filter(
            company=company,
            user__display__icontains=term,
            user__is_active=True
        )

class ExpenseTypeAsyncSearchView(DataAsyncSearchView):
    model = ExpenseType
    fields = ['name']

class BankAccountAsyncSearchView(AsyncSearchView):
    fields = ['name', 'bank', 'account_number', 'account_holder']

    def get_queryset(self, term, request):
        supplier_id = request.GET.get('supplier_id')

        queryset =  BankAccount.objects.filter(
            Q(name__icontains=term) |
            Q(account_number__icontains=term) |
            Q(account_holder__icontains=term),
            company=request.user.employee.company,
            status=BaseStatus.ACTIVE.name
        )

        if supplier_id:
            queryset = queryset.filter(
                partner__id=supplier_id,
                type=BankAccountType.PARTNER.name
            )
        else:
            queryset = queryset.filter(
                type=BankAccountType.INTERNAL.name
            )
        
        return queryset

    def get_bank(self, obj, context):
        return obj.bank.code

backend/sales/components/order/views.py
from core.utils.viewsets import ModelViewSet
from core.views_api import DataTableView
from sales.models import Order

from sales.constants import OrderStatus
from .serializers import *

class OrderViewSet(ModelViewSet):
    serializer_class = OrderSerializer
    queryset = Order.objects.all()

class OrderTableView(DataTableView):
    model = Order
    order_by = '-update_date'
    columns_def = [
        {
            'name': 'order_number',
            'title': 'Số đơn hàng',
            'width': '24%',
        },
        {
            'name': 'customer',
            'display_field': 'name',
            'title': 'Khách hàng',
            'width': '24%'
        },
        {
            'name': 'note',
            'title': 'Ghi chú',
            'orderable': False,
            'width': '24%'
        },
        {
            'name': 'status',
            'display_list': OrderStatus.choices(),
            'title': 'Trạng thái',
            'orderable': False,
            'width': '24%'
        },
        {
            'title': 'Thao tác',
            'orderable': False,
            'search': False,
            'css_class': 'text-center',
            'width': '4%'
        },
    ]

    def get_queryset(self, user, params):
        type_ = params.get('type', '')
        return Order.objects.filter(company=user.employee.company, type=type_.upper())

backend/purchase/templates/purchase/order/form.html
{% extends "app.html" %}

{% block body %}
{% with base_url='/purchase/order' %}

<div class="content p-3">  
  <div class="card shadow mb-4"> 
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Thông tin đơn hàng</h6>
    </div>
    <div class="card-body">
      <form id="fmt" method="POST" novalidate onsubmit="saveOrder(event)">
        <input type="hidden" name="pk" value="{{form.instance.pk|default:''}}">
        <table class="table table-form">
          <tbody>
            <tr>
              <th>Nhà cung cấp*:</th>
              <td>
                {{form.supplier}}
                <ul class="errorlist" data-for='supplier'></ul>
              </td>
            </tr>
            <tr>
              <th>Ghi chú:</th>
              <td>{{form.note}}</td>
            </tr>
          </tbody>
        </table>
        
        <div class="row">
          <div class="col">
            <h5>Chi tiết các mặt hàng</h5>
            <div class="float-end">
              <a class="btn btn-sm btn-primary mb-2" href="javascript:addOrderItem(-1)">
                <i class="fas fa-plus"></i> Thêm mặt hàng
              </a>
            </div>
          </div>
        </div>
        
        <div style="overflow-x: auto;">
          <table class="table" style="width: 150%;">
            <thead>
              <tr>
                <th></th>
                <th style="width: 35%;">Tên mặt hàng</th>
                <th style="width: 20%;" class="text-center">Đơn giá</th>
                <th style="width: 20%;" class="text-center">Số lượng</th>
                <th style="width: 20%;" class="text-center">Thành tiền</th>
              </tr>
            </thead>
            <tbody id="orderItems">
            </tbody>
          </table>
        </div>

        <div class="mt-3">
          <a class="btn btn-sm btn-secondary mr-1" href="{{ base_url }}">
            <i class="fas fa-arrow-left text-white-50"></i> Quay lại
          </a>

          <button type="submit" class="btn btn-sm btn-primary">
            <i class=" fas fa-save text-white-50"></i> Lưu lại
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
<script>
  let orderItems = [];

  function renderorderItem(index, orderItem) {
    return (`
      <tr id="row_${index}">
        <td class="text-center">
          <a class="me-2" href='javascript:deleteorderItem(${index})'>
            <i class="fas fa-trash text-danger"></i>
          </a>

          <a href='javascript:addorderItem(${index})'>
            <i class="fas fa-plus"></i>
          </a>
        </td>
        <td>
          <select name="order_items[].product"
            class='form-control select-product' 
          >
          </select>
          
          <ul class="errorlist" 
            data-for='order_items[${index}].product'>
          </ul>
        </td>
        <td class="text-center">
          <input type="number" min="0" step="1000" 
            name="order_items[].qty"
            class="form-control text-center price-unit"
            onchange="updatePriceUnit(${index}, value)"
            value="${orderItem.price_unit}"/>
          
          <ul class="errorlist" 
            data-for='order_items[${index}].price_unit'>
          </ul>
        </td>
        <td class="text-center">
          <input type="number" min="1"  
            name="order_items[].qty"
            class="form-control text-center"
            onchange="updateQty(${index}, value)"
            value="${orderItem.qty}"/>

          <ul class="errorlist" 
            data-for='order_items[${index}].qty'>
          </ul>
        </td>
        <td class="text-center">
          <span class="sub-total">
            ${getSubTotal(orderItem)}
          </span>
        </td>
      </tr>
    `)
  }

  function $_cell(rowIndex, selector) {
    return $(`#row_${rowIndex}`).find(selector);
  }

  function renderorderItems() {
    if(orderItems.length > 0) {
      let html = orderItems.map((orderItem, index) => 
                    renderorderItem(index, orderItem)).join('');

      $('#orderItems').html(html);
    
      orderItems.forEach((orderItem, index) => {
        let initialData;
        if(orderItem.product) {
          initialData = [{
            id: orderItem.product,
            name: orderItem.product_name,
            price_unit: orderItem.price_unit
          }];
        };

        $_cell(index, '.select-product').asyncSelect({
          url: '/purchase/order/search-product',
          displayFunc: item => item.name,
          onChange: (el, data) => updateProduct(index, el, data),
          initialData
        })
      });
    }else{
      $('#orderItems').html('<tr><td colspan="5">Chưa có mặt hàng nào</td></tr>');
    }
  }

  function getPriceUnit(orderItem) {
    if(orderItem.price_unit) {
      return orderItem.price_unit + ' đ';
    }
    return '';
  }

  function getSubTotal(orderItem) {
    if(orderItem.qty && orderItem.price_unit) {
      return (orderItem.qty * orderItem.price_unit) + ' đ';
    }
    return '';
  }

  function updateProduct(index, el, data) {
    data = data.length > 0? data[0] : {};
    let orderItem = orderItems[index];
    orderItem.product_name = data.name;
    orderItem.product = data.id;
    orderItem.price_unit = data.price_unit;
    
    $_cell(index, '.price-unit').val(orderItem.price_unit??'');
    $_cell(index, '.sub-total').html(getSubTotal(orderItem));
  }

  function updateQty(index, value) {
    let orderItem = orderItems[index];
    orderItem.qty = value;
    $_cell(index, '.sub-total').html(getSubTotal(orderItem));
  }

  function updatePriceUnit(index, value) {
    let orderItem = orderItems[index];
    orderItem.price_unit = value;
    $_cell(index, '.sub-total').html(getSubTotal(orderItem));
  }

  function addorderItem(index) {
    if(index == -1) {
      orderItems.push({qty: 1});
    }else{
      orderItems.splice(index+1, 0, {qty: 1});
    }

    renderorderItems();
  }

  function deleteorderItem(index) {
    orderItems.splice(index, 1);
    renderorderItems();
  }

  async function saveOrder(e) {
    e.preventDefault(); 

    let data = {
      ...serializeForm(document.getElementById('fmt')),
      order_items: orderItems,
    };

    $('.errorlist').empty();

    let resp = await $_post('/purchase/order/save', data);
    
    if(resp.ok) {
      location.href = '{{base_url}}';
    }else{
      handleErrorResponse(resp);
    }
  }

  $(document).ready(function(){
    $('#id_supplier').asyncSelect({
      url: `/purchase/order/search-supplier`,
      displayFunc: item => item.name,
    });
    
    orderItems = JSON.parse('{{order_items_json|safe}}');

    renderorderItems();
    
  });
</script>
{% endwith %}
{% endblock %}

backend/purchase/templates/purchase/order/list.html
{% extends "app.html" %}

{% block body %}
{% with base_url='/purchase/order' %}
<div class="content p-3">
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Danh sách đơn hàng</h6>
    </div>
    <div class="card-body">
      {% if user|has_permission:"purchase.add_order" %}
        <div class="mb-2">
          <a href='{{ base_url }}/create' class="btn btn-sm btn-primary">
            <i class="fas fa-plus text-white-50"></i> Thêm đơn hàng
          </a>
        </div>
      {% endif %}
      <div id="table-container" class="table-responsive1">
      </div>
    </div>
  </div>
</div>
<script>
$(document).ready(function () {
  createDataTable("#table-container", "{{base_url}}/search", {
    renders: {
      col4: function(data, row) {
        return (`
          <div class="dropdown">
            <a href='javascript:void(0)' data-bs-toggle="dropdown">
              <i class="fas fa-ellipsis-v"></i>
            </a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="view-detail/${row.pk}">
                Xem thông tin
              </a>

              {% if user|has_permission:"purchase.change_order" %}
                <a class="dropdown-item" href="update/${row.pk}">
                  Cập nhật
                </a>
              {% endif %}

              {% if user|has_permission:"purchase.delete_order" %}
                ${row.status_id == 'DRAFT' ?
                  `<a class="dropdown-item" href="javascript:deleteItem(${ row.pk })">
                    Xóa
                  </a>` : ''
                }
              {% endif %}
            </div>
          </div>
        `)
      }
    }
  });
});

async function deleteItem(id) {
  if (confirm("Bạn có muốn xóa đơn hàng này ?")) {
    var resp = await $_delete(`{{base_url}}/delete/${id}`);
    if (resp.ok) {
      location.reload();
    } else {
      alert("Lỗi xảy ra");
    }
  }
}
</script>
{% endwith %}
{% endblock %}